#!/usr/bin/env Rscript

# MSc Data Science (Full Time)
# PROM02 Computing Master's Project

# File Name: umbrella_module_perform_data_analysis.R
# File Author: William Whinn

##############
# References #
##############

# - https://tinyurl.com/yycfo2zh

#########
# Notes #
#########

# - This function will allow a user to analyse a data set, including randomly-
#   generated data, to highlight the layout and inform user-input for the
#   RandomWalk() function.
# - By providing an outline of these data, a user may 'bias' their Random Walk.
#   This is useful if there are clusters of communities and the user wishes to
#   traverse a particular cluster.
# - It is also possible to use this function to validate network data. Data sets
#   such as the Karate Club (Zachary) and the random data generated by Umbrella
#   (GenerateRandomNetworkFile()) are all of type 'list'. This function will
#   terminate if data are provided in an incompatible format.

#############
# Functions #
#############

PerformDataAnalysis <- function(dataset)
{
  ###################
  # Data Validation #
  ###################

  if (missing(dataset))
  {
    # FAILURE: Data have not been provided. Terminate analysis.
    print(paste("ERROR: Argument 'dataset' has not been defined. Terminating",
                "Data Analysis."))
    return()
  }
  else if (typeof(dataset) == 'list')
  {
    # SUCCESS: Data exists and is in the correct format.
    print("NOTE: Data is of type 'List'. Performing Data Analysis.")

    # NOTES:
    # - Continue outside of IF statement.
    # - Error conditions will terminate data analysis.

    data_type <- class(dataset)
  }
  else
  {
    # FAILURE: Catch unknown error.
    print("ERROR: An unknown error occurred. Terminating Data Analysis.")
    return()
  }

  #################
  # Data Analysis #
  #################

  print("NOTE: Validation Complete. Listing results:")

  # Display type and class of data.
  print(paste("Data Type:", data_type))

  # Data Preview
  print(head(dataset, 1))
}
