#!/usr/bin/env Rscript

# MSc Data Science (Full Time)
# PROM02 Computing Master's Project

# File Name: umbrella_module_perform_data_analysis.R
# File Author: William Whinn

##############
# References #
##############

# - https://tinyurl.com/yycfo2zh

#########
# Notes #
#########

# - This function will allow a user to analyse a data set, including randomly-
#   generated data, to highlight the layout and inform user-input for the
#   RandomWalk() function.
# - By providing an outline of these data, a user may 'bias' their Random Walk.
#   This is useful if there are clusters of communities and the user wishes to
#   traverse a particular cluster.
# - It is also possible to use this function to validate network data. Data sets
#   such as the Karate Club (Zachary) and the random data generated by Umbrella
#   (GenerateRandomNetworkFile()) are all of type 'list'. This function will
#   terminate if data are provided in an incompatible format.

#############
# Functions #
#############

AnalyseData <- function(dataset,
                        draw_graph = c(TRUE, FALSE),
                        random_seed = c(TRUE, FALSE))
{
  #################################
  # Argument Parsing: random_seed #
  #################################

  if (isTRUE(random_seed))
  {
    umbrella::ApplyRandomSeed()
  }
  else if (isFALSE(random_seed))
  {
    print(paste("NOTE: Argument 'random_seed' is set to 'FALSE'. Proceeding ",
                "with machine default."))
  }
  else if (missing(random_seed))
  {
    print(paste("NOTE: Argument 'random_seed' is missing. Proceeding with ",
                "machine default."))
  }
  else
  {
    # FAILURE: Catch unknown error.
    print("ERROR: An unknown error occurred. Terminating Data Analysis.")
    return()
  }

  #############################
  # Argument Parsing: dataset #
  #############################

  if (missing(dataset))
  {
    # FAILURE: Data have not been provided. Terminate analysis.
    print(paste("ERROR: Argument 'dataset' has not been defined. Terminating",
                "Data Analysis."))
    return()
  }
  else if (typeof(dataset) == 'list')
  {
    # SUCCESS: Data exists and is in the correct format.
    print("NOTE: Data is of type 'list'.")

    # NOTES:
    # - Continue outside of IF statement.
    # - Error conditions will terminate data analysis.

    data_type <- class(dataset)
  }
  else
  {
    # FAILURE: Catch unknown error.
    print("ERROR: An unknown error occurred. Terminating Data Analysis.")
    return()
  }

  #################
  # Data Analysis #
  #################

  print("NOTE: Validation Complete. No errors encountered.")

  if (class(dataset) == 'data.frame')
  {
    # SUCCESS: Convert data into correct format for network analysis.
    print(paste("NOTE: Data are 'data.frame' format. Converting to 'igraph'."))

    dataset <- igraph::graph_from_adj_list(dataset, mode = 'out',
                                           duplicate = FALSE)

    print(paste("NOTE: Data have been converted to 'igraph'."))
  }
  else if (class(dataset) == 'igraph')
  {
    # SUCCESS: No data conversion required.
    print(paste("NOTE: Data are 'igraph' format. No conversion required."))
  }
  else
  {
    # FAILURE: Catch unknown error.
    print("ERROR: An unknown error occurred. Terminating Data Analysis.")
    return()
  }

  # Get number of edges (connections) within the graph object.
  print(paste("NOTE: Data contains a total of", igraph::ecount(dataset),
              "edges (connections)."))

  # Get number of vertices (nodes) within the graph object.
  print(paste("NOTE: Data contains a total of", igraph::vcount(dataset),
              "vertices (nodes)."))

  ################################
  # Argument Parsing: draw_graph #
  ################################

  if (isTRUE(draw_graph))
  {
    igraph::plot.igraph(dataset,
                        main = 'Network Data Graph',
                        sub = paste("Umbrella", packageVersion("umbrella")))
  }

  ###############
  # Return Data #
  ###############

  # NOTES:
  # - Return data quietly.
  # - This allows assignment to variable.

  invisible(dataset)
}

################
# TESTING CODE #
################

UmbrellaTestFunction <- function()
{
  # NOTES:
  # - This function was written to test 'umbrella' under Linux.
  #   - MS Windows may not function correctly due to differing file structure.
  # - This function will be removed before final release.
  # - No data will be exported to the current R session.

  # WARNING:
  # - This function writes a file to the user's "$HOME" directory.

  print("########## TEST CODE ##########")

  setwd("~/")
  umbrella::GenerateRandomNetworkFile()
  test_data <- read.csv('umbrella_random_network.csv')
  umbrella::AnalyseData(test_data, draw_graph = TRUE)

  # Convert 'test_data' into a graph object.
  print("TEST: Convert comma-separated data into graph object.")
  test_data <- igraph::graph_from_adj_list(test_data, mode = 'out',
                                           duplicate = FALSE)

  # Convert 'test_data' into adjacency matrix.
  print("TEST: Convert data into adjacency matrix.")
  test_data <- igraph::as_adjacency_matrix(test_data, type = 'both')
  print("TEST: Outputting data as adjacency matrix.")
  print(test_data)

  # Convert 'test_data' back into original format.
  print("TEST: Convert data back into graph object.")
  test_data <- igraph::graph_from_adjacency_matrix(test_data)

  # Plot the final resutls.
  print("TEST: Plot the reconverted graph object to test conversion.")
  igraph::plot.igraph(test_data,
                      main = 'Network Data Graph / UmbrellaTestFunction()',
                      sub = paste("Umbrella", packageVersion("umbrella")))

  ###############
  # Return Data #
  ###############

  # NOTES:
  # - Return data quietly.
  # - This allows assignment to variable.

  print("TEST: Return data as graph object.")
  print(test_data)
  invisible(test_data)
}

# End of File.
